name: Checking uat PR

on:
  pull_request:
    types: [opened, reopened]


jobs:
  check_is_downmerge_running:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          echo "boli boli boli"
          sleep 10
          echo ${{secrets.GITHUB_TOKEN}}
          git config user.name "mkozub-tb"
          git config user.email "marcin.kozub@thinkbeyond.cloud"
          git clone https://mkozub-tb:${{secrets.GITHUB_TOKEN}}@github.com/mkozub-tb/testestest.git testFolder
          cd testFolder
          git checkout main

      - name: Checking
        run: |
          # COMMIT_SHA=${{ github.event.pull_request.head.sha }}
          PR_BRANCH=github.event.pull_request.head.ref
          
          # Use GitHub API to get the workflow runs for the branch
          WORKFLOW_RUNS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/actions/runs?event=push&branch=$PR_BRANCH")

          # Check if there are any running workflows for the branch
          if [[ $(echo "$WORKFLOW_RUNS" | jq '.workflow_runs | length') -gt 0 ]]; then
            echo "Workflows are running on branch $PR_BRANCH"
            echo "::set-output name=workflowRunning::true"
          else
            echo "No workflows running on branch $PR_BRANCH"
            echo "::set-output name=workflowRunning::false"
          fi
