name: Checking uat PR

on:
  pull_request:
    types: [opened, reopened]


jobs:
  check_is_downmerge_running:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          echo "boli boli boli"
          echo ${{secrets.GITHUB_TOKEN}}
          git config user.name "mkozub-tb"
          git config user.email "marcin.kozub@thinkbeyond.cloud"
          git clone https://mkozub-tb:${{secrets.GITHUB_TOKEN}}@github.com/mkozub-tb/testestest.git testFolder
          cd testFolder
          git checkout main

      - name: Checking
        run: |
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          COMMIT_SHA=${{ github.event.pull_request.head.sha }}
          STATE="success"  # Can be "success", "failure", "pending", etc.
          CONTEXT="custom-check-v2"  # A unique identifier for your status
          PR_BRANCH=${{ github.event.pull_request.base.ref }}
          
          # Use GitHub API to get the workflow runs for the branch
          WORKFLOW_RUNS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/actions/runs?event=push&branch=$PR_BRANCH")

          # Check if there are any running workflows for the branch
          if [[ $(echo "$WORKFLOW_RUNS" | jq '.workflow_runs | length') -gt 0 ]]; then
            echo "Workflows are running on branch $PR_BRANCH"
          else
            echo "No workflows running on branch $PR_BRANCH"
            
            curl -X POST "https://api.github.com/repos/$GITHUB_REPOSITORY/statuses/$COMMIT_SHA" \
              -H "Authorization: token $GITHUB_TOKEN" \
              -d "{\"state\":\"$STATE\",\"context\":\"$CONTEXT\",\"description\":\"Custom status for the current pull request\"}"
          fi
